In [2]:
import numpy as np
x = np.float32(1.0)
x

1.0

In [3]:
y = np.int_([1, 2 ,4 ])
y

array([1, 2, 4])

In [6]:
np.array([1, 2, 3], dtype='f')

array([1., 2., 3.], dtype=float32)

2. Overflow Errors

In [7]:
np.power(100, 8, dtype=np.int64)

10000000000000000

In [8]:
np.power(100, 8, dtype=np.int32)

1874919424

i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )

In [6]:
import numpy as np

array = np.array([1, 2, 3, 4, 5 ])
print(array.dtype)

int32


3.Get the data type of an array containing strings:

In [9]:
import numpy as np

arr = np.array (['Egg', 'Milk', 'Apple', 'Orange'])

print(arr.dtype)

<U6


4. Create an array with data type 4 bytes integer:

In [12]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6], dtype='i4')
print(arr)

print(arr.dtype)

[1 2 3 4 5 6]
int32


5. Change data type from float to integer by using 'i' as parameter value:

In [15]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1, 4.1, 5.4])
newarray = arr.astype('i')
print(newarray)
print(newarray.dtype)

[1 2 3 4 5]
int32


6.Change data type from float to integer by using int as parameter value:

In [17]:
import numpy as np

arr = np.array ([1.2, 4.5, 6.7])
newarray = arr.astype(int)
print(newarray)
print(newarray.dtype)

[1 4 6]
int32


6. Make a view, change the original array, and display both arrays:

In [19]:
arr = np.array([1, 2, 3, 4, 5, 6])

x = arr.view()

arr[0] = 45

print(arr)
print(x)

[45  2  3  4  5  6]
[45  2  3  4  5  6]


7. Make Changes in the VIEW:

In [21]:
import numpy as np 

arr = np.array([1, 2, 3, 4, 5, 6, 7])
x = arr.view()
x[0] = 40
print(arr)
print(x)

#Print the value of the base attribute to check if an array owns it's data or not:

import numpy as np 

arr = np.array ([1,2, 3, 4, 5, 6, 7])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

[40  2  3  4  5  6  7]
[40  2  3  4  5  6  7]
None
[1 2 3 4 5 6 7]


8.Searching Arrays

In [23]:
import numpy as np

arr = np.array([2, 3, 4, 5, 6, 6, 4,7, 7])
arr = np.where (arr ==4)
print(x)

[1 2 3 4 5 6 7]


In [29]:
#Find the indexes where the values are even:

import numpy as np

arr = np.array([1, 2, 3 ,4 , 5, 6, 7, 8])

x = np.where(arr%2 == 0)
print(x)

(array([1, 3, 5, 7], dtype=int64),)
