1.  Create a basic array

In [87]:
import numpy as np

In [88]:
a = np.array([1, 2, 3, 4])

1.2 create an array filled with 0’s:

In [89]:
np.zeros(2)
np.array([0., 0.])

array([0., 0.])

In [90]:
np.ones(4)
np.array([1., 1.])

array([1., 1.])

1.3 Create an empty array with 3 elements:

In [91]:
np.empty(3)
np.array([3.12, 32. , 1. ])

array([ 3.12, 32.  ,  1.  ])

2. We can also use np.linspace() 
to create an array with values that are spaced linearly in a specified interval:

np.linspace(0, 10, num=5)
array([0. , 1.6, 6. , 4.5, 9.])

2.1 Specifying your data type

default data type is floating point (np.float64), you can explicitly specify which data type you want

In [92]:
x = np.ones(2, dtype=np.int64)
x 
np.array([2, 2])

array([2, 2])

2.2 Adding, removing, and sorting elements

In [93]:
value = np.array([3, 4, 5, 6, 7, 8, 9])


In [94]:
np.sort(value)
np.array([1, 2, 3, 4, 5, 6, 7, 8])

array([1, 2, 3, 4, 5, 6, 7, 8])

2.3 we can quickly sort the numbers in ascending order with:

In [95]:
np.sort(value)
np.array([1, 2, 3, 4, 5, 6, 7, 8])

array([1, 2, 3, 4, 5, 6, 7, 8])

3. we can concatenate them with np.concatenate().

In [96]:
x = np.array ([2, 3, 4, 5, 6])
y = np.array( [7, 8, 9, 10, 11])

np.concatenate((x, y))


array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [97]:
x = np.array([[2, 3], [4,5]])
y = np.array([[6, 7]])

np.concatenate((x, y), axis=0)


array([[2, 3],
       [4, 5],
       [6, 7]])

In [98]:
array_example = np.array([[[0, 1, 2, 3],
                            [4, 5, 6, 7]],

                            [[0, 1, 2, 3],
                             [4, 5, 6, 7]],

                            [[0, 1, 2, 3],
                             [4, 5, 6, 7]]])

                             


In [99]:
array_example.ndim

3

In [100]:
array_example.size

24

In [101]:
array_example.shape

(3, 2, 4)

4. Using arr.reshape() will give a new shape to an array without changing the data

In [102]:
a = np.arange(6)
print(a)


[0 1 2 3 4 5]


4. With np.reshape, you can specify a few optional parameters:

In [103]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [104]:
np.reshape(a, newshape=(1, 6), order='C')
np.array([[0, 1, 2, 3, 4, 5]])

array([[0, 1, 2, 3, 4, 5]])

5. Convert a 1D array into a 2D array (how to add a new axis to an array)

In [105]:
a = np.array([1, 2, 3, 4, 5 ,6, ])
a.shape

(6,)

In [106]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [107]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

5. For a column vector, you can insert an axis along the second dimension:

In [108]:
col_vector = a[:, np.newaxis]
col_vector.shape
(6, 1)

(6, 1)

In [109]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

5.1 We can use np.expand_dims to add an axis at index position 1 with:

In [110]:
x = np.expand_dims(a, axis=0)
x.shape

(1, 6)

6. Indexing 

In [111]:
data = np.array([3, 4, 5, 6, 7])

data[1]

4

5.2 slicing

In [112]:
data[0:3]

array([3, 4, 5])

In [113]:
data[1:]

array([4, 5, 6, 7])

In [114]:
data[-4:]

array([4, 5, 6, 7])

In [115]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])


In [116]:
print(a[a <5])

[1 2 3 4]


In [117]:
five_up = (a >= 5)
print (a[five_up])

[ 5  6  7  8  9 10 11 12]


7.WE can select elements that are divisible by 2:

In [118]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


8. we can select elements that satisfy two conditions using the & and | operators:

In [119]:
x = a[(a > 2) & (a < 10)]
print(x)

[3 4 5 6 7 8 9]


In [120]:
six_up = (a > 4) | ( a == 6)
print(six_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [121]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])


In [122]:
y = np.nonzero (a < 5 )
print(y)

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))


In [123]:
not_there = np.nonzero( a == 43)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


9.1 How to create an array from existing data

In [124]:
a = np.array ([ 1, 2, 3, 4, 5, 6 ,7, 8 , 9, 10, 11])

In [125]:
value1 = a[3:9]
value1

array([4, 5, 6, 7, 8, 9])

In [126]:
a1 = np.array([[1, 1],
                [2, 2]])

a2 = np.array([[3, 3],
                [4, 4]])

In [127]:
a1 = np.array([[2, 1],
                [2, 2]])

a2 = np.array([[2, 3],
                [4, 4]])

In [128]:
a1 = np.array([[4, 1],
                [2, 2]])

a2 = np.array([[7, 3],
                [9, 4]])

In [129]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

11. We can also stack two existing arrays, both vertically and horizontally. Let’s say you have two arrays, a1 and a2:

In [130]:
x1 = np.array([[1, 1],
                [2, 4]])
y1 = np.array(([3, 5],
                [6, 7]))

In [132]:
# stack them vertically with vstack

np.stack((x1, y1))

array([[[1, 1],
        [2, 4]],

       [[3, 5],
        [6, 7]]])

In [133]:
#or stack them horizentally with hstack

np.hstack((x1, y1))

array([[1, 1, 3, 5],
       [2, 4, 6, 7]])

In [137]:
#we can  split an array into several smaller arrays using hsplit.

x = np.arange(1, 25).reshape(2, 12)
print(x)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


11.1 If we wanted to split this array into three equally shaped arrays, we can run:

In [138]:
np.hsplit(x , 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [139]:
#Split your array after the third and forth column

np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [141]:
b = np.array([[1, 1], [2, 2]])

In [142]:
b.sum(axis=0)

array([3, 3])

In [143]:
b.sum(axis=1)

array([2, 4])

In [144]:
#Broadcasting

data = np.array([1.0, 2.0])
data * 1.8

array([1.8, 3.6])

In [145]:
data.max()
data.min()
data.sum()

3.0

In [146]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [147]:
a.sum()

4.8595784

In [148]:
a.min()

0.05093587

In [149]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

12. Creating Matrices

In [150]:
###can pass Python lists of lists to create a 2-D array (or “matrix”) to represent them in NumPy.


data= np.array([[1, 2], [3, 4], [5,6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [151]:
np.ones((4, 3, 2, 1))

array([[[[1.],
         [1.]],

        [[1.],
         [1.]],

        [[1.],
         [1.]]],


       [[[1.],
         [1.]],

        [[1.],
         [1.]],

        [[1.],
         [1.]]],


       [[[1.],
         [1.]],

        [[1.],
         [1.]],

        [[1.],
         [1.]]],


       [[[1.],
         [1.]],

        [[1.],
         [1.]],

        [[1.],
         [1.]]]])

In [152]:
np.ones(4)

array([1., 1., 1., 1.])

In [154]:
np.ones((4, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

13. Generating random numbers

In [161]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [162]:
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [164]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [166]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [167]:
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [170]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


14. Transposing and reshaping a matrix

In [172]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [174]:
data.reshape(3, 2 )

array([[1, 2],
       [3, 4],
       [5, 6]])

In [177]:
arr = np.arange(6).reshape((2, 3))
print(arr)

[[0 1 2]
 [3 4 5]]


In [178]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [179]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

15. Reverse an array

In [180]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [183]:
reversed_arr = np.flip(arr)

In [184]:
print('Reversed Array:', reversed_arr)


Reversed Array: [8 7 6 5 4 3 2 1]


13. Reshaping and flattening multidimensional arrays

In [187]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [188]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [189]:
a1 = x.flatten()
a1[0]
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [190]:
a2 = x.ravel()
a2[0] = 98
print(x)

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [191]:
a = np.array([1, 2, 3, 4, 5, 6, 7])
np.save('filename', a)

In [193]:
b = np.load('filename.npy') 

In [194]:
print(b)

[1 2 3 4 5 6 7]


In [195]:
csv_arr = np.array([1, 2, 3, 4, 6, 6, 7, 8])

np.savetxt('new_file.csv', csv_arr)

In [196]:
np.loadtxt('new_file.csv')

array([1., 2., 3., 4., 6., 6., 7., 8.])

In [197]:
import pandas as pd

15. Arrays

In [201]:
a1D = np.array([1, 2, 3, 4])
a2D = np.array([[1, 2], [3,4]])
a3D = np.array([[[1, 2], [3, 4], [5,6], [7,8 ]]])

In [202]:
a = np.array ([127, 128, 129])
a

array([127, 128, 129])

16. When you use numpy.array to define a new array, you should consider the dtype of the elements in the array, which can be specified explicitly.If you are not careful with dtype assignments, you can get unwanted overflow, as such

In [205]:
a = np.array([127, 128, 129], dtype=np.int8)
a

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_21988\337030010.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 128 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  a = np.array([127, 128, 129], dtype=np.int8)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_21988\337030010.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 129 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  a = np.array([127, 128, 129], dtype=np.int8)


array([ 127, -128, -127], dtype=int8)

In [208]:
a = np.array([2, 3, 4], dtype=np.uint32)
b = np.array([5, 6, 7], dtype=np.uint32)
c_unsigned32 = a - b

In [210]:
print('unsignged c:', c_unsigned32, c_unsigned32.dtype)

unsignged c: [4294967293 4294967293 4294967293] uint32


In [211]:
#1d Array creation functions

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [216]:
np. arange(2, 3, 0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

15.1 numpy.linspace will create arrays with a specified number of elements, and spaced equally between the specified beginning and end values. For example:

In [217]:
np.linspace(1., 4., 6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

15.3 (2 - 2D array creation functions)

In [218]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [219]:
np.eye(3, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [221]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [222]:
np.diag([1, 2, 3], 1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [223]:
a = np.array([[1, 2], [3, 4]])
np.diag(a)

array([1, 4])

In [226]:
np.vander(np.linspace(0, 2, 5), 2)

array([[0. , 1. ],
       [0.5, 1. ],
       [1. , 1. ],
       [1.5, 1. ],
       [2. , 1. ]])

In [230]:
np.vander([1, 2, 3, 4], 2)

array([[1, 1],
       [2, 1],
       [3, 1],
       [4, 1]])

In [231]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [233]:
np.indices((3, 3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [238]:
a = np.array([1, 2, 3, 4, 5, 6, ])
b = a[:2]
b += 1
print('a =', a, ' n=', b)

a = [2 3 3 4 5 6]  n= [2 3]


In [240]:
a = np.array([1, 2, 3, 4])
b = a[:2].copy()
b += 1
print('a = ', a, 'b = ' , b)

a =  [1 2 3 4] b =  [2 3]


In [244]:
a = np.ones((2, 2))
b = np.eye(2, 2)
c = np.zeros((2, 2))
d = np.diag((-3, - 4))
np.block([[a, b ], [c, d ]])

array([[ 1.,  1.,  1.,  0.],
       [ 1.,  1.,  0.,  1.],
       [ 0.,  0., -3.,  0.],
       [ 0.,  0.,  0., -4.]])