1.  Create a basic array

In [42]:
import numpy as np

In [43]:
a = np.array([1, 2, 3, 4])

1.2 create an array filled with 0’s:

In [44]:
np.zeros(2)
np.array([0., 0.])

array([0., 0.])

In [45]:
np.ones(4)
np.array([1., 1.])

array([1., 1.])

1.3 Create an empty array with 3 elements:

In [46]:
np.empty(3)
np.array([3.12, 32. , 1. ])

array([ 3.12, 32.  ,  1.  ])

2. We can also use np.linspace() 
to create an array with values that are spaced linearly in a specified interval:

np.linspace(0, 10, num=5)
array([0. , 1.6, 6. , 4.5, 9.])

2.1 Specifying your data type

default data type is floating point (np.float64), you can explicitly specify which data type you want

In [47]:
x = np.ones(2, dtype=np.int64)
x 
np.array([2, 2])

array([2, 2])

2.2 Adding, removing, and sorting elements

In [48]:
value = np.array([3, 4, 5, 6, 7, 8, 9])


In [49]:
np.sort(value)
np.array([1, 2, 3, 4, 5, 6, 7, 8])

array([1, 2, 3, 4, 5, 6, 7, 8])

2.3 we can quickly sort the numbers in ascending order with:

In [50]:
np.sort(value)
np.array([1, 2, 3, 4, 5, 6, 7, 8])

array([1, 2, 3, 4, 5, 6, 7, 8])

3. we can concatenate them with np.concatenate().

In [51]:
x = np.array ([2, 3, 4, 5, 6])
y = np.array( [7, 8, 9, 10, 11])

np.concatenate((x, y))


array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [52]:
x = np.array([[2, 3], [4,5]])
y = np.array([[6, 7]])

np.concatenate((x, y), axis=0)


array([[2, 3],
       [4, 5],
       [6, 7]])

In [53]:
array_example = np.array([[[0, 1, 2, 3],
                            [4, 5, 6, 7]],

                            [[0, 1, 2, 3],
                             [4, 5, 6, 7]],

                            [[0, 1, 2, 3],
                             [4, 5, 6, 7]]])

                             


In [54]:
array_example.ndim

3

In [55]:
array_example.size

24

In [56]:
array_example.shape

(3, 2, 4)

4. Using arr.reshape() will give a new shape to an array without changing the data

In [57]:
a = np.arange(6)
print(a)


[0 1 2 3 4 5]


4. With np.reshape, you can specify a few optional parameters:

In [58]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [59]:
np.reshape(a, newshape=(1, 6), order='C')
np.array([[0, 1, 2, 3, 4, 5]])

array([[0, 1, 2, 3, 4, 5]])

5. Convert a 1D array into a 2D array (how to add a new axis to an array)

In [60]:
a = np.array([1, 2, 3, 4, 5 ,6, ])
a.shape

(6,)

In [61]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [62]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

5. For a column vector, you can insert an axis along the second dimension:

In [63]:
col_vector = a[:, np.newaxis]
col_vector.shape
(6, 1)

(6, 1)

In [64]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

5.1 We can use np.expand_dims to add an axis at index position 1 with:

In [65]:
x = np.expand_dims(a, axis=0)
x.shape

(1, 6)

6. Indexing 

In [66]:
data = np.array([3, 4, 5, 6, 7])

data[1]

4

5.2 slicing

In [67]:
data[0:3]

array([3, 4, 5])

In [68]:
data[1:]

array([4, 5, 6, 7])

In [69]:
data[-4:]

array([4, 5, 6, 7])

In [70]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])


In [71]:
print(a[a <5])

[1 2 3 4]


In [72]:
five_up = (a >= 5)
print (a[five_up])

[ 5  6  7  8  9 10 11 12]


7.WE can select elements that are divisible by 2:

In [73]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


8. we can select elements that satisfy two conditions using the & and | operators:

In [74]:
x = a[(a > 2) & (a < 10)]
print(x)

[3 4 5 6 7 8 9]


In [75]:
six_up = (a > 4) | ( a == 6)
print(six_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [76]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])


In [77]:
y = np.nonzero (a < 5 )
print(y)

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))


In [78]:
not_there = np.nonzero( a == 43)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


9.1 How to create an array from existing data

In [79]:
a = np.array ([ 1, 2, 3, 4, 5, 6 ,7, 8 , 9, 10, 11])

In [80]:
value1 = a[3:9]
value1

array([4, 5, 6, 7, 8, 9])

In [81]:
a1 = np.array([[1, 1],
                [2, 2]])

a2 = np.array([[3, 3],
                [4, 4]])

In [83]:
a1 = np.array([[2, 1],
                [2, 2]])

a2 = np.array([[2, 3],
                [4, 4]])

In [85]:
a1 = np.array([[4, 1],
                [2, 2]])

a2 = np.array([[7, 3],
                [9, 4]])

In [86]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])